export const IS_PRODUCTION = process.env.NODE_ENV === 'production'
export const IS_MOBILE = window.matchMedia('(pointer:coarse)').matches
export const TILESET_FILENAME = 'tileset.png'

export const IMPORT_PREVIEW_WIDTH = 550
export const IMPORT_PREVIEW_HEIGHT = 300

export enum THEMES {
    DARK = 'dark',
    LIGHT = 'light'
}

export enum IMPORT_MODES {
    NEW_PROJECT = 'NEW_PROJECT',
    NEW_LAYER = 'NEW_LAYER',
    NEW_IMAGE = 'NEW_IMAGE'
}

export const DEFAULT_TILESET_IMAGE = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAAAQCAYAAACRBXRYAAAABmJLR0QA/wD/
  AP+gvaeTAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAIUlEQVRo3u3BAQ0AAADCoPdPbQ43oAAAAAAAAAAAAIB3AygQAAHhiTg6AAAAAElFTkSuQmCC`

export const TRANSPARENCY_BG_LIGHT_IMG = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAAI0lEQVQY
  02P8//8/AxJ4+PAhMpeJAS+gqTQLmlvk5eUHi9MAcYAIts0d55YAAAAASUVORK5CYII=`

export const TRANSPARENCY_BG_DARK_IMG = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAAI0lEQVQY02
  OMiYlmQAIfPnxE5jIx4AU0lWZBc4uAAP9gcRoAWzIG+m7Xy5gAAAAASUVORK5CYII=`

// Palettes
export * as PALETTES from './palettes'
